# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About Me"
  url = "#about"
  weight = 10

[[main]]
  name = "Posts"
  url = "blog/"
  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 40

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

[[main]]
  name = "Resources"
  url = "resources/"
  identifier = "resources"
  weight = 70

[[main]]
  name = "CodeLabs"
  url = "resources/codelabs/"
  parent = "resources"
  weight = 71

[[main]]
  name = "Guides"
  url = "resources/guides/"
  parent = "resources"
  weight = 72

[[main]]
  name = "SlideDecks"
  url = "resources/slidedecks/"
  parent = "resources"
  weight = 73

[[main]]
  name = "Webinars"
  url = "resources/webinars/"
  parent = "resources"
  weight = 74

[[main]]
  name = "Lesson Plans"
  url = "resources/lessonplans/"
  parent = "resources"
  weight = 75

[[main]]
  name = "Notes"
  url = "resources/notes/"
  parent = "resources"
  weight = 76

[[main]]
  name = "Community Resource Library"
  url = "resources/communityresourcelibrary/"
  parent = "resources"
  weight = 77
